version: 2
updates:
  - package-ecosystem: "cargo"
    directort: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
  # - package-ecosystem: "cargo"
  #   directort: "cli/"
  #   schedule:
  #     interval: "weekly"
  #   target-branch: "main"
  #   ignore:
  #     - dependency-name: "repository"
  # - package-ecosystem: "cargo"
  #   directort: "gui/"
  #   schedule:
  #     interval: "weekly"
  #   target-branch: "main"
  #   ignore:
  #     - dependency-name: "repository"
  # - package-ecosystem: "cargo"
  #   directort: "repository/"
  #   schedule:
  #     interval: "weekly"
  #   target-branch: "main"
