[workspace]
members = [
    "repository",
    "cli",
]
default-members = ["cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/stdonnelly/ats-tracking-system"
