[workspace]
members = [
    "repository",
    "cli", "gui",
]
default-members = ["cli", "gui"]
resolver = "2"

[workspace.package]
version = "0.6.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/stdonnelly/ats-tracking-system"
