[package]
name = "ats-tracking-system"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
mysql = "25.0.1"
opener = "0.7.2"
tempfile = "3.12.0"
time = { version = "0.3.36", features = ["default", "local-offset", "macros", "parsing"] }
