[package]
name = "repository"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mysql = "25.0.1"
time = { version = "0.3.36", features = ["default", "local-offset", "macros", "parsing"] }
