import { StandardButton, Button } from "std-widgets.slint";
export component DeleteConfirmation inherits Dialog {
    in property <int> id;
    callback delete_clicked <=> delete.clicked;

    title: "Delete job application?";

    Text {
        text: @tr("Are you sure you want to delete this job application? ({})", id);
    }

    StandardButton {
        kind: cancel;
    }

    delete := Button {
        text: "Delete";
        dialog-button-role: accept;
    }
}
