// Functions used in multiple places in the application

import { Date } from "std-widgets.slint";

import { HumanResponseView } from "./models.slint";

export global Logic {
    pure callback date-diff(Date, Date) -> int;

    public pure function human-response-to-string(hr: HumanResponseView) -> string {
        if (hr == HumanResponseView.None) {
            "No response yet"
        } else if (hr == HumanResponseView.Rejection) {
            "Rejection"
        } else if (hr == HumanResponseView.InterviewRequest) {
            "Interview request"
        } else if (hr == HumanResponseView.InterviewedThenRejected) {
            "Interviewed then rejected"
        } else if (hr == HumanResponseView.JobOffer) {
            "Job offer"
        } else {
            "ERROR"
        }
    }

    public pure function string-to-human-response(s: string) -> HumanResponseView {
        if (s == "Rejection") {
            HumanResponseView.Rejection;
        } else if (s == "Interview request") {
            HumanResponseView.InterviewRequest;
        } else if (s == "Interviewed then rejected") {
            HumanResponseView.InterviewedThenRejected;
        } else if (s == "Job offer") {
            HumanResponseView.JobOffer;
        } else {
            // Fallback to None if None or not recognized
            HumanResponseView.None;
        }
    }

    // Use `s` if `hr` is not None, otherwise use an empty string
    public pure function display-if-human-response(hr: HumanResponseView, s: string) -> string {
        if (hr != HumanResponseView.None) {
            s
        } else {
            ""
        }
    }

    public pure function display-if-nonzero(n: int) -> string {
        if (n != 0) {
            n
        } else {
            ""
        }
    }
}
